"""Themed initial names for onboarded agents."""

from __future__ import annotations

import random
from collections.abc import Callable

AGENT_NAME_POOL: tuple[str, ...] = (
    "Ada",
    "Amundsen",
    "Anning",
    "Archimedes",
    "Aristarchus",
    "Armstrong",
    "Avicenna",
    "Battuta",
    "Bering",
    "Bohr",
    "Brahe",
    "Burnell",
    "Cabot",
    "Carson",
    "Cook",
    "Copernicus",
    "Cousteau",
    "Curie",
    "Darwin",
    "Dirac",
    "Drake",
    "Earhart",
    "Einstein",
    "Euclid",
    "Euler",
    "Faraday",
    "Fermat",
    "Fermi",
    "Fibonacci",
    "Fleming",
    "Flinders",
    "Fourier",
    "Franklin",
    "Gagarin",
    "Galileo",
    "Gauss",
    "Goodall",
    "Hamilton",
    "Hawking",
    "Heisenberg",
    "Herschel",
    "Heyerdahl",
    "Hillary",
    "Hopper",
    "Hubble",
    "Hudson",
    "Hypatia",
    "Jemison",
    "Johnson",
    "Kepler",
    "Khwarizmi",
    "Lagrange",
    "Laplace",
    "Leavitt",
    "Leibniz",
    "Lindbergh",
    "Lister",
    "Lovelace",
    "Magellan",
    "Maxwell",
    "McClintock",
    "Meitner",
    "Mendel",
    "Nansen",
    "Newton",
    "Noether",
    "Pascal",
    "Pasteur",
    "Payne",
    "Planck",
    "Poincare",
    "Pythagoras",
    "Ramanujan",
    "Ride",
    "Riemann",
    "Rubin",
    "Rutherford",
    "Sagan",
    "Schrodinger",
    "Scott",
    "Shackleton",
    "Tereshkova",
    "Tesla",
    "Turing",
    "Vesalius",
    "Vespucci",
    "Volta",
    "Watt",
    "Wu",
    "Yeager",
    "Zhang",
    "Zheng",
    "Amaterasu",
    "Anansi",
    "Anubis",
    "Apollo",
    "Ares",
    "Artemis",
    "Athena",
    "Atlas",
    "Aurora",
    "Baldur",
    "Bastet",
    "Brigid",
    "Ceres",
    "Demeter",
    "Diana",
    "Eos",
    "Freya",
    "Frigg",
    "Fuxi",
    "Gaia",
    "Guanyin",
    "Heimdall",
    "Helios",
    "Hephaestus",
    "Hera",
    "Hermes",
    "Horus",
    "Idun",
    "Iris",
    "Isis",
    "Janus",
    "Kali",
    "Lakshmi",
    "Loki",
    "Lugh",
    "Luna",
    "Maui",
    "Mazu",
    "Merlin",
    "Minerva",
    "Morpheus",
    "Nike",
    "Nuwa",
    "Odin",
    "Osiris",
    "Pandora",
    "Persephone",
    "Prometheus",
    "Quetzal",
    "Ra",
    "Saraswati",
    "Sedna",
    "Sekhmet",
    "Selene",
    "Skadi",
    "Sol",
    "Susanoo",
    "Thoth",
    "Titan",
    "Tsukuyomi",
    "Tyr",
    "Vesta",
    "Vulcan",
    "Zephyr",
    "Zeus",
)


def generate_agent_name(
    *, taken: Callable[[str], bool], rng: random.Random | None = None
) -> str:
    chooser = rng or random.SystemRandom()
    candidates = list(AGENT_NAME_POOL)
    chooser.shuffle(candidates)
    for candidate in candidates:
        if not taken(candidate):
            return candidate
    base = candidates[0]
    suffix = 2
    while taken(f"{base} {suffix}"):
        suffix += 1
    return f"{base} {suffix}"
