from __future__ import annotations

from typing import Any, Protocol


class SessionStore(Protocol):
    def create_session(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def append_event(
        self, session_id: str, event: dict[str, Any]
    ) -> dict[str, Any]: ...
    def get_session(self, session_id: str) -> dict[str, Any]: ...
    def delete_session(self, session_id: str) -> None: ...
    def list_sessions(self) -> list[dict[str, Any]]: ...
    def create_artifact(
        self, session_id: str, payload: dict[str, Any]
    ) -> tuple[dict[str, Any], dict[str, Any]]: ...
    def write_artifact(
        self, session_id: str, payload: dict[str, Any]
    ) -> dict[str, Any]: ...
    def index_workspace_artifact(
        self, session_id: str, artifact: dict[str, Any], content: bytes | None
    ) -> tuple[dict[str, Any], dict[str, Any]]: ...
    def read_artifact_content(
        self, session_id: str, artifact_id: str
    ) -> bytes | None: ...


class TaskStore(Protocol):
    def get_task(self, task_id: str) -> dict[str, Any]: ...
    def list_tasks(self) -> list[dict[str, Any]]: ...
    def link_session(self, task_id: str, session_id: str) -> dict[str, Any]: ...
    def unlink_session(self, task_id: str, session_id: str) -> dict[str, Any]: ...
    def append_event(self, task_id: str, event: dict[str, Any]) -> dict[str, Any]: ...
    def record_activity(
        self, task_id: str, message: str, payload: dict[str, Any] | None = None
    ) -> dict[str, Any]: ...
